---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: ../../data_bags

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[opsline-chef-backup::default]
  - name: backup
    run_list:
      - recipe[opsline-chef-backup::backup]
  - name: restore
    run_list:
      - recipe[opsline-chef-backup::restore]